### PR TITLE
Bugfix: Don't try to submit empty searches

### LINKED ISSUE #266: [Bug]: trying to expand search phone immediately searches for ""
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

_No response_

### STEPS TO REPRODUCE

1. Open blocks on mobile
2. Click search icon in header to expand search input
3. See "no results" page

### EXPECTED BEHAVIOR

_No response_

### PR DESCRIPTION
**Pull request by csillag**
This fixes the bug of not being able to expand the search field on mobile.

Fixes #266

### CODE REVIEW

File: src/app/components/Search/index.tsx [hunk 1]
```diff
@@ -113,7 +113,9 @@ const SearchCmp: FC<SearchProps> = ({ scope, variant, disabled, onFocusChange: o
 
   const onFormSubmit = (e?: FormEvent) => {
     e?.preventDefault()
-    navigate(RouteUtils.getSearchRoute(scope, value))
+    if (value) {
```
Comment (lukaw3d) [inline src/app/components/Search/index.tsx:116]: Downside of this: it doesn't offer search suggestions

**Review by lukaw3d — APPROVED** [review]
