### PR TITLE
Fix Safari buggy display of block fill

### LINKED ISSUE #1114: [Bug]: Safari on iOS buggy display of block fill (VerticalProgressBar)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

_No response_

### STEPS TO REPRODUCE

File

### EXPECTED BEHAVIOR

_No response_

### PR DESCRIPTION
**Pull request by buberdds**
Closes #1114

Tested using MacOS Safari and Iphone 15 Safari (mobile via Browserstack)
Screenshot from 2024-01-26 11-19-06

### CODE REVIEW

File: src/app/components/ProgressBar/index.tsx [hunk 1]
```diff
@@ -1,14 +1,29 @@
...
+
+export const VerticalProgressBar: FC<VerticalProgressBarProps> = ({ value }) => {
+  return (
+    <Box sx={{ width: barSize, height: barSize, transform: 'rotate(-90deg)' }}>
+      <StyledVerticalProgressBar variant="determinate" value={value} />
+    </Box>
+  )
+}
+
+export const StyledVerticalProgressBar = styled(MuiLinearProgress)(() => ({
```
Comment (lukaw3d) [inline src/app/components/ProgressBar/index.tsx:21]: Probably don't want to export this one.
(and the name implies `styled(VerticalProgressBar)`)

**Review by lukaw3d — APPROVED** [review]
