### PR TITLE
Hide the transaction list when there are no transactions

### LINKED ISSUE #450: [Bug]: Don't show block transactions when there are none
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

Usually we list the transactions within a block, but sometimes there are none. In those cases we show a useless empty block.

### STEPS TO REPRODUCE

Visit https://explorer.dev.oasis.io/mainnet/emerald/blocks/5251038

### EXPECTED BEHAVIOR

We get
image

The "transactions' panel at the bottom is useless, and should be hidden.

### PR DESCRIPTION
**Pull request by csillag**
Fixes #450.

### CODE REVIEW

File: src/app/pages/BlockDetailPage/index.tsx [hunk 1]
```diff
@@ -111,9 +112,13 @@ export const BlockDetailView: FC<{
 
       <dt>{t('common.transactions')}</dt>
       <dd>
-        <Link href={transactionsAnchor}>
-          {t('common.transactionsNumber', { count: block.num_transactions })}
-        </Link>
+        {!!block.num_transactions ? (
```
Comment (buberdds) [inline src/app/pages/BlockDetailPage/index.tsx:115]: lint Redundant double negation

Comment (csillag) [reply src/app/pages/BlockDetailPage/index.tsx]: Sorry, fixed.

**Review by buberdds — APPROVED** [review]

File: src/app/pages/BlockDetailPage/index.tsx [hunk 2]
```diff
@@ -111,9 +112,13 @@ export const BlockDetailView: FC<{
...
       <dd>
-        <Link href={transactionsAnchor}>
-          {t('common.transactionsNumber', { count: block.num_transactions })}
-        </Link>
+        {block.num_transactions ? (
+          <Link href={transactionsAnchor}>
+            {t('common.transactionsNumber', { count: block.num_transactions })}
+          </Link>
+        ) : (
+          transactionLabel
```
[the remark this answers is not in the document]
Comment (csillag) [reply src/app/pages/BlockDetailPage/index.tsx:120]: Correct. I was distracted and forgot where I was.  Cleanup in https://github.com/oasisprotocol/explorer/pull/454.
