### PR TITLE
Use proper checksum ETH address format in Runtime events

### LINKED ISSUE #1141: [Bug]: Addresses in EVM events are not displayed with capitalization checksum
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SUMMARY

_No response_

### STEPS TO REPRODUCE

- https://explorer.dev.oasis.io/testnet/sapphire/address/0x000000000000000000000000000000000000dEaD
- image

### EXPECTED BEHAVIOR

0x000000000000000000000000000000000000dEaD

### PR DESCRIPTION
**Pull request by csillag**
Closes #1141.

### CODE REVIEW

File: src/app/components/Account/AccountLink.tsx [hunk 1]
```diff
@@ -7,6 +7,8 @@ import { RouteUtils } from '../../utils/route-utils'
 import Typography from '@mui/material/Typography'
 import { COLORS } from '../../../styles/theme/colors'
 import { SearchScope } from '../../../types/searchScope'
+import { isValidEthAddress } from '../../utils/helpers'
+import { toChecksumAddress } from '@ethereumjs/util'
 
 export const AccountLink: FC<{
```
Comment (lukaw3d) [inline src/app/components/Account/AccountLink.tsx:13]: Copy To Clipboard still copies non-checksum address.
And I don't think CopyToClipboard component should be doing transformations, so the best place to convert is in useGetRuntimeEvents, but it's also the hardest; event body is `any` and different event types have different fields.

Comment (csillag) [reply src/app/components/Account/AccountLink.tsx:13]: > Copy To Clipboard still copies non-checksum address.

Indeed. Do we want it something else? I assumed we want the checksum format for displaying only.

> I don't think CopyToClipboard component should be doing transformations,

Nor do I, that's why I added it to the `AccountLink` component.

>  so the best place to convert is in useGetRuntimeEvents,

I'm not sure about that. We are using `AccountLink` in many other places, too, where it's not related to runtime event. To me, `AccountLink` seems to be the natural choice.

> but it's also the hardest; event body is any and different event types have different fields.

When formatting runtime events, when we know that the type is address, we always use `AccountLink` for displaying, so adding it here seems to solve the `any` problem as well as we currently can.

Comment (lukaw3d) [reply src/app/components/Account/AccountLink.tsx:13]: I think it should copy checksum format too. API returns checksum format everywhere else, so display and copy of e.g. addresses in Transaction Details are both in checksum format. Same in list of Tokens.

Comment (csillag) [reply src/app/components/Account/AccountLink.tsx]: >  the best place to convert is in useGetRuntimeEvents

OK, moved tra transformation into `useGetRuntimeEvents`.

File: src/oasis-nexus/api.ts [hunk 2]
```diff
@@ -714,6 +723,7 @@ export const useGetRuntimeEvents: typeof generated.useGetRuntimeEvents = (
               ) {
                 return {
                   ...event,
+                  evm_log_params: event.evm_log_params?.map(fixChecksumAddressInEvmEventParam),
```
Comment (lukaw3d) [inline src/oasis-nexus/api.ts:726]: oh, it's this easy. No need to check event types because 0x addresses only appear in evm.log params. Not in e.g. `body` of consensus_accounts.deposit

**Review by lukaw3d — APPROVED** [review]

File: src/oasis-nexus/api.ts (hunk 2 above)
Comment (csillag) [reply src/oasis-nexus/api.ts:726]: Indeed.
